kapost/circuitry

- README.md
- lib/circuitry/publisher.rb
- lib/circuitry/subscriber.rb
@kapost/core This adds support for timing out message processing on both the publisher and subscriber.  Resolves #11.  /cc @pk-nb
> Timeout if publishing or subscribing exceeds a threshold

- lib/circuitry/version.rb
Bump version to include the lock strategy and timeout changes.
> Bump version to 1.2.0

- README.md
Accidentally used `Lock` instead of `Locks` everywhere in the readme.
> Fix references to lock classes in readme

- lib/circuitry/subscriber.rb
- lib/circuitry/version.rb
- spec/circuitry/subscriber_spec.rb
@kapost/core We're currently raising a number of service errors that are expected to happen intermittently (internal server error, service unavailable, & timeouts).  These errors are temporary and expected to happen on occasion, so we should do nothing beyond returning the same way we would when no messages are available.
* Note about [internal error & service unavailable error](https://aws.amazon.com/articles/Amazon-SQS/1343#13)
* Note about [service timeouts](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html)
I've also bumped the version to 1.2.2.
> Ignore temporary service errors

- lib/circuitry/subscriber.rb
- lib/circuitry/version.rb
@kapost/core @iamnader Sometimes SQS resets the connection while we're waiting for any pending messages.  We should handle this gracefully rather than terminating the subscriber loop.
> Handle excon error for "connection reset by peer"

- .codeclimate.yml
- README.md
- lib/circuitry/configuration.rb
- lib/circuitry/processors/forker.rb
- lib/circuitry/processors/threader.rb
- lib/circuitry/version.rb
- spec/circuitry/processors/forker_spec.rb
- spec/circuitry/processors/threader_spec.rb
@kapost/core This will allow us to hook into circuitry threads and forks to close database connections properly.  The fork option might not be as useful since, for example, unicorn offers `before_fork` and `after_fork` blocks.  I thought it would still be useful to include them for the sake of completeness though.
> Add thread and fork exit hooks

- README.md
- lib/circuitry/locks/redis.rb
@kapost/core This permits the redis lock strategy to utilize the [ConnectionPool gem](https://github.com/mperham/connection_pool) instead of a single redis connection.  Thoughts?
> Enable redis connection pooling

- circuitry.gemspec
- spec/circuitry/locks/redis_spec.rb
- spec/spec_helper.rb
@kapost/core This adds some tests I neglected to include when implementing redis connection pooling.
> Add tests for redis connection pool

- circuitry.gemspec
- lib/circuitry/subscriber.rb
- spec/circuitry/subscriber_spec.rb
@kapost/core I'm seeing some stack traces in Honeybadger that relate to temporary connection issues when deleting a message after handling is completed.  This is less than ideal since it means a message could be processed multiple times.
This change will allow deletes to be retried when a temporary issue is encountered.  Interested in feedback.
> Retry deletes after successful processing

- .codeclimate.yml
- circuitry.gemspec
- lib/circuitry/configuration.rb
- lib/circuitry/message.rb
- lib/circuitry/publisher.rb
- lib/circuitry/services/sns.rb
- lib/circuitry/services/sqs.rb
- lib/circuitry/subscriber.rb
- lib/circuitry/topic_creator.rb
- spec/circuitry/configuration_spec.rb
- spec/circuitry/message_spec.rb
- spec/circuitry/publisher_spec.rb
- spec/circuitry/services/sns_spec.rb
- spec/circuitry/services/sqs_spec.rb
- spec/circuitry/subscriber_spec.rb
- spec/circuitry/topic_creator_spec.rb
@kapost/core @alexmcpherson @paul This replaces the fog-aws gem with aws-sdk.  The reasoning behind this is that long polling was introduced in SQS API version 2012-11-05, and fog is using version 2009-02-01.  Essentially, the long polling code in the gem is not working as intended, and new connections are being opened rapidly before closing almost immediately while waiting for messages.
~~This is a WIP because I need to check into the `CONNECTION_ERRORS` code to see if I need to map that over from the fog-aws gem, or if the aws-sdk gem takes care of that logic for us already.  I think it may be the latter.~~
> Replace fog-aws with aws-sdk

- .rubocop.yml
- README.md
- bin/console
- circuitry.gemspec
- exe/circuitry
- lib/circuitry.rb
- lib/circuitry/cli.rb
- lib/circuitry/concerns/async.rb
- lib/circuitry/configuration.rb
- lib/circuitry/provisioner.rb
- lib/circuitry/publisher.rb
- lib/circuitry/queue.rb
- lib/circuitry/queue_creator.rb
- lib/circuitry/subscriber.rb
- lib/circuitry/subscription_creator.rb
- lib/circuitry/topic_creator.rb
- lib/circuitry/version.rb
- lib/tasks/circuitry_tasks.rake
- spec/circuitry/cli_spec.rb
- spec/circuitry/configuration_spec.rb
- spec/circuitry/queue_creator_spec.rb
- spec/circuitry/subscriber_spec.rb
- spec/circuitry/subscription_creator_spec.rb
- spec/circuitry_spec.rb
Adds a few QoL fixes to Amazon provisioning
- Resolves competing provisioning code between CLI and rake task in previous PR
- Changes the interface for Circuitry.subscribe to not use a queue url in favor of a config variable (circuitry subscribers should only have one queue), and bumps version to 2.0 due to this change.
- Resolves a bunch of rubocop issues
> Auto provisioning via rake+CLI, subscriber/topic config

- README.md
@brandonc Your yaml example in the readme had bad topic names for the production environment.  This should help to clarify how this is expected to work.
> Fixed readme example for production topic names

- README.md
- lib/circuitry/testing.rb
@brandonc This provides simple mocking for tests in third-party apps.  (We've got a custom mock in studio at the moment, which this would take the place of.)
> Added mocks for third-party testing

- lib/circuitry/config/shared_settings.rb
- lib/circuitry/middleware/chain.rb
- lib/circuitry/middleware/entries/flush.rb
- spec/circuitry/middleware/entries/flush_spec.rb
@brandonc @ianisborn This adds a new flush middleware to the publisher & subscriber middleware chains.  This ensures that any new circuitry messages enqueued while receiving or sending another message also gets delivered.  Previously, this had to be handled in the following manner (like Ian had to include in studio):
```ruby
Circuitry.subscribe do |message, topic|
handle(handler, topic_name(topic), message)
Circuitry.flush
end
```
> Added flush middleware

- lib/circuitry/provisioning/provisioner.rb
- spec/circuitry/provisioning/provisioner_spec.rb
- spec/circuitry/provisioning/subscription_creator_spec.rb
- spec/circuitry/provisioning_spec.rb
@kapost/core This change permits an app to only publish without subscribing to a queue.  Currently, the provisioner breaks down because it expects queue_name to always be set.
> Updated to permit subscription only (no queue name requirement)

- CHANGELOG.md
- README.md
- lib/circuitry/config/publisher_settings.rb
- lib/circuitry/config/shared_settings.rb
- lib/circuitry/config/subscriber_settings.rb
- lib/circuitry/middleware/entries/flush.rb
- spec/circuitry/config/publisher_settings_spec.rb
- spec/circuitry/config/subscriber_settings_spec.rb
- spec/circuitry/middleware/chain_spec.rb
- spec/circuitry/middleware/entries/flush_spec.rb
- spec/fixtures/test_middleware.rb
- spec/spec_helper.rb
- spec/support/examples/settings_examples.rb
@brandonc I've been thinking about this since we talked yesterday.  This middleware works as a subscriber middleware, but not as a publisher middleware.  The stack overflow issue will not occur on the subscriber side (no publish -> flush -> publish loop), and I think it actually does make sense here.  Would like to revisit.  No rush.
> Revisit flush middleware on subscribers

- lib/circuitry/publisher.rb
We're seeing some of these "internal failure" errors on SNS, which is a 500 error.  In general, we should be retrying any errors that are 5XX errors since it's not necessarily and issue with the request itself.
This adds the associated error class to the list of retriable errors.  It also adds a small amount of back-off to the retry block.
> Updated publisher retries to handle internal error with backoff

- README.md
- circuitry.gemspec
- lib/circuitry/provisioning/provisioner.rb
- lib/circuitry/provisioning/subscription_creator.rb
- lib/circuitry/tasks.rb
1. Missing requires for `circuitry` and `logger` were added for `rake circuitry:setup` to run in a non-Rails app.
1. Removed `:environment` as a prerequisite task since that only exists in Rails apps and isn't needed.
1. We now check if `topics` are configured during provisioning before creating a policy since attempting to add a policy with no topics results in an AWS error being thrown.
1. The `thor` gem needs to be a runtime dependency (rather than development dependency) in order for `circuitry help provision` to work.
1. Added a line to README that demonstrates how to include circuitry rake tasks in your project.
> Fix rake circuitry:setup issues

- lib/circuitry/tasks.rb
When I removed the `:environment` task dependency as [part of this commit](https://github.com/kapost/circuitry/pull/56/commits/66408fc852240f74dbe6ffcf7ac1857a9ac63e5d), it fixed the task for pure Ruby apps, but it prevented initializers from loading in Rails apps.  Since an initializer is the likely place that the circuitry configuration is defined, it's important that we run that task in order to look at the proper AWS config, queue name, topics, etc.
*TODO: test this in plain Ruby and Rails apps before merging/releasing.*
> Fixed rails environment loading for setup rake task

- CHANGELOG.md
- circuitry.gemspec
- lib/circuitry/tasks.rb
- lib/circuitry/version.rb
- spec/spec_helper.rb
This fixes an issue with the Rails `environment` rake task not being executed before `circuitry:setup` in newer versions of rake.  /cc @BlueVajra this is what you ran into recently as well.
> Fixed environment rake task invokation for circuitry:setup

- lib/circuitry/subscriber.rb
- spec/circuitry/subscriber_spec.rb
`Aws::SQS::Types::Message` returns different responses as `messages` depending on `batch_size`.
For a `batch_size` of 1, AWS returns
```
{
:message_id => "one",
:receipt_handle => "test receipt handle",
:md5_of_body => "test md5",
:body => "text for body",
:attributes => {
"SenderId" => "sender123",
"ApproximateFirstReceiveTimestamp" => "1493921572480",
"ApproximateReceiveCount" => "2",
"SentTimestamp" => "1493921111028"
},
:md5_of_message_attributes => nil,
:message_attributes => {}
}
```
which has problems when cast to an `Array`.
```
[
[0] "one",
[1] "test receipt handle",
[2] "test md5",
[3] "text for body",
[4] {
"SenderId" => "sender123",
"ApproximateFirstReceiveTimestamp" => "1493921572480",
"ApproximateReceiveCount" => "2",
"SentTimestamp" => "1493921111028"
},
[5] nil,
[6] {}
] …
```
> Handle single message response from AWS

- README.md
- lib/circuitry/config/shared_settings.rb
- lib/circuitry/publisher.rb
- lib/circuitry/subscriber.rb
This is just to add some documentation for the `use_iam_profile` option as requested in #61
> readme for 'Allow option to use IAM instance profile credentials'

- lib/circuitry/config/shared_settings.rb
- lib/circuitry/publisher.rb
- lib/circuitry/subscriber.rb
This is done entirely in the AWS SDK, and requires no work on the gem's part.
> Allow option to use IAM instance profile credentials

- .circleci/config.yml
- circle.yml
CircleCI is sunsetting 1.0 configs and builds effective August 31, 2018. This gets circuitry on Circle 2.0
https://kapost.atlassian.net/browse/DEVOPS-1043
> circle 2.0

- lib/circuitry/publisher.rb
- lib/circuitry/subscriber.rb
This message creates a ton of info level logs, since, unlike the other info level log entries (queue subscribe, queue unsubscribe, etc), there is one log entry per message published.
In thinking about how to categorize log entries, I really like looking to Java's log4j, which defines info and debug as follows:
**Debug:** Designates fine-grained informational events that are most useful to debug an application.
**Info:** Designates informational messages that highlight the progress of the application at coarse-grained level.
I propose that any per-message log entries should be logged at a debug level, to better conform to the definitions above, and so as not to generate tons of logs in a production system.
> Change info log entries to debug when they relate to a specific message that's being enqueued or dequeued

- CHANGELOG.md
- lib/circuitry/publisher.rb
- lib/circuitry/version.rb
- spec/circuitry/publisher_spec.rb
- spec/circuitry/subscriber_spec.rb
* When published, will official release https://github.com/kapost/circuitry/pull/70/commits.
Tested it locally with other Kapost apps that use circuitry and worked fine.
* Improve error message when the sqs message is invalid, for example too large. The
exception will have the actual message available so we can debug the source.
> Version 3.3.0

- CHANGELOG.md
- README.md
- lib/circuitry/config/shared_settings.rb
- spec/circuitry/config/publisher_settings_spec.rb
- spec/circuitry/config/subscriber_settings_spec.rb
Adds an option `aws_options_overrides` that accepts a hash of options to merge with the default options passed to the subscriber or publisher clients
Currently, the only settings passed through are [`access_key_id`, `secret_access_key` and `region`](https://github.com/kapost/circuitry/blob/master/lib/circuitry/config/shared_settings.rb#L26-L32)
However, there are many others that it may be useful to override. See:
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SNS/Client.html
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/Client.html
For example, the `endpoint` option can enable developers to develop using [`localstack`](https://github.com/localstack/localstack) without needing to connect to real AWS/SNS services.
> Allow AWS client options overrides for publisher/subscriber

- CHANGELOG.md
- lib/circuitry/version.rb
- Officially releases https://github.com/kapost/circuitry/pull/80
which adds `aws_options_overrides` to aws clients
- I went with a minor version since it's an enhancement.
> Bump gem version to `3.4.0`
